#version 460

#extension GL_EXT_ray_tracing : enable

struct hitPayload
{
  vec3 hitValue;
};

layout(binding = 0, set = 0) uniform accelerationStructureEXT topLevelAS;
layout(binding = 1, set = 0, rgba8) uniform image2D image;
layout(binding = 0, set = 1) uniform CameraProperties 
{
	mat4 viewInverse;
	mat4 projInverse;
} cam;

layout(location = 0) rayPayloadEXT hitPayload prd;

void main()
{
	const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5f);
	const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);

	vec2 d = inUV * 2.0 - 1.0;

	vec4 origin		= cam.viewInverse * vec4(0, 0, 0, 1);
	vec4 target		= cam.projInverse * vec4(d.x, d.y, 1, 1);
	vec4 direction	= cam.viewInverse * vec4(normalize(target.xyz), 0);

	float tmin = 0.001f;
	float tmax = 10000.f;

	uint  rayFlags = gl_RayFlagsOpaqueEXT;

    traceRayEXT(
		topLevelAS, 
		rayFlags, 
		0xff, 
		0, 
		0, 
		0, 
		origin.xyz, 
		tmin, 
		direction.xyz, 
		tmax, 
		0
	);

	imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(prd.hitValue, 0.0));
}